version: 0.0
os: linux
files:
  - source: /tmp/codigo/hola-v2.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy-scripts/before_install.sh
      timeout: 300
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy-scripts/validation.sh
      timeout: 300
      runas: root
